plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version "${forge_gradle_version}"
    id 'org.spongepowered.mixin' version "${mixin_gradle_version}"
    id 'com.github.johnrengelman.shadow' version "${shadow_gradle_version}"
}

version = "${minecraft_version}-${mod_version}"
group= "${package_group}" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "${mod_name}"

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

minecraft {
    mappings channel: mappings_channel, version: mappings_version
	
    accessTransformer = files('src/main/resources/jei_at.cfg')
    
    runs {
        client {
            jvmArg "-Dfml.coreMods.load=${mixin_loader_class}"
            jvmArg "-Dmixin.hotSwap=true"
            jvmArg "-Dmixin.checks.interfaces=true"

            workingDirectory project.file('run')

            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
			environment 'MC_VERSION', "${minecraft_version}"
        }

        server {
            workingDirectory project.file('run')

            jvmArg "-Dfml.coreMods.load=${mixin_loader_class}"
            jvmArg "-Dmixin.hotSwap=true"
            jvmArg "-Dmixin.checks.interfaces=true"

            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
			environment 'MC_VERSION', "${minecraft_version}"
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
	maven { 	
		url = "https://dvs1.progwml6.com/files/maven"
	}
	maven {
		name = "CurseMaven"
		url = "https://www.cursemaven.com/"
	}
	flatDir {
		dirs 'libs'
	}
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    shadow "org.spongepowered:mixin:${mixin_version}"
    annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"

	compileOnly fg.deobf("mezz.jei:jei_${minecraft_version}:${jei_version}:api")	// compile against the JEI API
	runtimeOnly fg.deobf("mezz.jei:jei_${minecraft_version}:${jei_version}")  // at runtime, use the full JEI jar
	
    implementation fg.deobf("curse.maven:baubles-${baubles_version}")
    implementation fg.deobf("curse.maven:xat-${xat_version}")
    implementation fg.deobf("curse.maven:potioncore-${potioncore_version}")
    implementation fg.deobf("curse.maven:qualitytools-${qualitytools_version}")
    implementation fg.deobf("curse.maven:reachfix-${reachfix_version}")
    implementation fg.deobf("curse.maven:rlcombat-${rlcombat_version}")
    implementation fg.deobf("curse.maven:spartanhudbaubles-${spartanhudbaubles_version}")
}

mixin {
    add sourceSets.main, "${mod_id}.mixin.refmap.json"
}

processResources {
    var replaceProperties = [
            'mod_version': mod_version
    ]

    inputs.properties replaceProperties
	duplicatesStrategy = DuplicatesStrategy.INCLUDE
	exclude 'jei_at.cfg'
    
    filesMatching('mcmod.info') {
        expand replaceProperties
    }
}

shadowJar {
    configurations = [project.configurations.shadow]
    mergeServiceFiles()

    exclude 'org/spongepowered/asm/launch/MixinLaunchPlugin*'
    exclude 'org/spongepowered/asm/launch/MixinTransformationService*'
    exclude 'org/spongepowered/asm/launch/platform/container/ContainerHandleModLauncherEx*'

    exclude 'LICENSE.txt'

    archiveClassifier.set('')
}

reobf {
    shadowJar {}
}

jar {
    manifest {
        attributes([
                'FMLCorePlugin': mixin_loader_class,
                'FMLCorePluginContainsFMLMod': 'true',
                'ForceLoadAsMod': 'true',
                'TweakClass': 'org.spongepowered.asm.launch.MixinTweaker'
        ])
    }

    archiveClassifier.set('1.12.2-THIN')
}

build.dependsOn(shadowJar)
jar.finalizedBy('reobfJar')