org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.java.installations.auto-download=false

minecraft_version=1.12.2

forge_gradle_version=6.0.+
forge_version=14.23.5.2860
mappings_channel=stable
mappings_version=39-1.12

mixin_gradle_version=0.7.+
mixin_version=0.8.5
mixin_loader_class=com.oblivioussp.spartanweaponry.mixin.MixinLoader

shadow_gradle_version=8.1.1

mod_id=spartanweaponry
mod_name=SpartanWeaponry
mod_version=1.6.1
package_group=com.oblivioussp.spartanweaponry

jei_version=4.11.0.202
baubles_version=227083:2518667
xat_version=279900:4469269
potioncore_version=242872:2905184
qualitytools_version=264756:2732994
reachfix_version=556777:4344825
rlcombat_version=711714:5940474
spartanhudbaubles_version=557117:3566426